from mongoengine import *
#from django.db import models

class Exchange(Document):
    buyer = StringField(required=False) 
    seller = StringField(required=False)
    seller_2 = StringField(required=False)
    cat_date = StringField(required=False)
    institution = StringField(required=False)
    catalogue_id = StringField(required=False)
    cat_lot_num = StringField(required=False)
    price = StringField(required=False)
    sold = StringField(required=False)
    comments = StringField(required=False)

class Manuscript(Document):
    currency = StringField(required=False)
    source = StringField(required=False)
    columns = StringField(required=False)
    duplicate_ms = StringField(required=False)
    manuscript_id = StringField(required=False)
    current_location = StringField(required=False)
    author = StringField(required=False)
    author_variant = StringField(required=False)
    title = StringField(required=False)
    language = StringField(required=False)
    material = StringField(required=False)
    place = StringField(required=False)
    use = StringField(required=False)
    date = StringField(required=False)
    circa = StringField(required=False)
    artist = StringField(required=False)
    script = StringField(required=False)
    folios = StringField(required=False)
    lines = StringField(required=False)
    height = StringField(required=False)
    width = StringField(required=False)
    binding = StringField(required=False)
    provenance = StringField(required=False)
    link = StringField(required=False)
    full_page_mini = StringField(required=False)
    large_mini = StringField(required=False)
    small_mini = StringField(required=False)
    mini = StringField(required=False)
    historiated_initials = StringField(required=False)
    decorated_initials = StringField(required=False)
    possible_duplicates = StringField(required=False)

    exchanges = ListField(ReferenceField(Exchange), required=False)

class Transaction(Document):
    buyer = StringField(required=False) 
    seller = StringField(required=False)
    seller_2 = StringField(required=False)
    cat_date = StringField(required=False)
    institution = StringField(required=False)
    catalogue_id = StringField(required=False)
    cat_lot_num = StringField(required=False)
    price = StringField(required=False)
    sold = StringField(required=False)
    comments = StringField(required=False)
    currency = StringField(required=False)
    source = StringField(required=False)
    columns = StringField(required=False)
    duplicate_ms = StringField(required=False)
    manuscript_id = StringField(required=False)
    current_location = StringField(required=False)
    author = StringField(required=False)
    author_variant = StringField(required=False)
    title = StringField(required=False)
    language = StringField(required=False)
    material = StringField(required=False)
    place = StringField(required=False)
    use = StringField(required=False)
    date = StringField(required=False)
    circa = StringField(required=False)
    artist = StringField(required=False)
    script = StringField(required=False)
    folios = StringField(required=False)
    lines = StringField(required=False)
    height = StringField(required=False)
    width = StringField(required=False)
    binding = StringField(required=False)
    provenance = StringField(required=False)
    link = StringField(required=False)
    full_page_mini = StringField(required=False)
    large_mini = StringField(required=False)
    small_mini = StringField(required=False)
    mini = StringField(required=False)
    historiated_initials = StringField(required=False)
    decorated_initials = StringField(required=False)
    possible_duplicates = StringField(required=False)
